# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f217e8882b463f92b6921c1b69951d43a614fb6d8c26f62988ad0a7ad1f58d6d73c4ded78118ddb4bc913949f76c3181efe4ccee35636fb7c5eab8a9b4583014

test:
  secret_key_base: 535af9b6d153f69937e73ced6d924b8ba167008aee21c19a76e1bd6acb584f3f10df352a802fb8c00b044c095ccb03ce319c1138683156944a9bc2507986bc1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
